# Site settings
title: Detekcia výtlkov
email: monika.sanyova@gmail.com
description: Stránka o mojej bakalárskej práci vytvorená použitím generátora statických stránok Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
my_name: Monika Sanyová
my_email: monika.sanyova@gmail.com
