# Site settings
title: Detekcia výtlkov
email: monika.sanyova@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stránka o mojej bakalárskej práci vytvorená použitím generátora statických stránok Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
my_name: Monika
my_email: monika.sanyova@gmail.com

# Build settings
markdown: kramdown
